name: API CI
on:
  push:
    paths:
      - 'apps/api/**'
  pull_request:
    paths:
      - 'apps/api/**'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: safe
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install
        run: bun install --frozen-lockfile
        working-directory: apps/api
      - name: Generate Prisma
        run: bunx prisma generate
        working-directory: apps/api
      - name: Typecheck
        run: bunx tsc --noEmit
        working-directory: apps/api
